[package]
name = "flag_experiments"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies.third_crate]
path = "./third_crate"

[dependencies.other_crate]
path = "./other_crate"

[dependencies.gflags]
path = "./gflags"
