[package]
name = "flag_example"
version = "0.1.0"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
lazy_static = "*"

[dependencies.zcfg]
path = "../zcfg"

[dependencies.zcfg_flag_parser]
path = "../zcfg_flag_parser"
